/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlbumDialog: typeof import('./components/AlbumDialog.vue')['default']
    Banner: typeof import('./components/Banner.vue')['default']
    CartMenu: typeof import('./components/CartMenu.vue')['default']
    Categories: typeof import('./components/Categories.vue')['default']
    CheckoutProduct: typeof import('./components/CheckoutProduct.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    CustomCalendar: typeof import('./components/CustomCalendar.vue')['default']
    EventDialog: typeof import('./components/EventDialog.vue')['default']
    EventList: typeof import('./components/EventList.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    'IconMdi:chevronRight': typeof import('~icons/mdi/chevron-right')['default']
    IconMdiArrowRight: typeof import('~icons/mdi/arrow-right')['default']
    IconMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IconMdiClose: typeof import('~icons/mdi/close')['default']
    IconMdiMenu: typeof import('~icons/mdi/menu')['default']
    LeftSection: typeof import('./components/LeftSection.vue')['default']
    LoaderOverlay: typeof import('./components/LoaderOverlay.vue')['default']
    LoginDialog: typeof import('./components/LoginDialog.vue')['default']
    MediaGallery: typeof import('./components/MediaGallery.vue')['default']
    MembershipForm: typeof import('./components/MembershipForm.vue')['default']
    NavigationDrawer: typeof import('./components/NavigationDrawer.vue')['default']
    NotFound404: typeof import('./components/NotFound404.vue')['default']
    ProductCard: typeof import('./components/ProductCard.vue')['default']
    ReAuthenticationDialog: typeof import('./components/ReAuthenticationDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snackbar: typeof import('./components/Snackbar.vue')['default']
    SponsorCard: typeof import('./components/SponsorCard.vue')['default']
    SubBanner: typeof import('./components/SubBanner.vue')['default']
    UploadDialog: typeof import('./components/UploadDialog.vue')['default']
    UploadSignatureInput: typeof import('./components/UploadSignatureInput.vue')['default']
    VerificationDialog: typeof import('./components/VerificationDialog.vue')['default']
  }
}
